#!/bin/sh

# TODO: if command is not found and fzf doesn't match it try to use git normally
#	if that returns suggestions (e.g. did you mean log) then parse those and fzf

gitf_folder="$(dirname "$(readlink -f "$0")")"
scripts_folder="${gitf_folder}/scripts"

function getFile () {
	cmd="$1"
	if [ -x "${scripts_folder}/${cmd}" ]
	then
		echo "${scripts_folder}/${cmd}"
	else
		file="$(ls "${scripts_folder}" | fzf -1 -q "${cmd}")"
		success="$?"
		printf "%s/%s\n" "${scripts_folder}" "${file}"
		return "${success}"
	fi
}

case "$1" in
	-h|--help)
		echo TODO
		exit 0
	;;
	*)
		cmd="$1"
		shift

		# TODO: show preview of --help of that command & allow executing it with different arguments
		if file="$(getFile "${cmd}")"
		then
			bash "${file}" "$@"
		else
			echo "No command specified. gitf aborted"
		fi
esac
